//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Multiple_Choice_A
    {
        public int Answer_Id { get; set; }
        public Nullable<int> Answer { get; set; }
        public Nullable<int> Question_Id { get; set; }
        public Nullable<int> Percent { get; set; }
    
        public virtual Multiple_Choice_Q Multiple_Choice_Q { get; set; }
    }
}
