//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question_Ans1
    {
        public int Question_Id { get; set; }
        public string Question { get; set; }
        public Nullable<int> Answer { get; set; }
        public Nullable<int> Percentage { get; set; }
    }
}
